###################################
# Fetch all third party libraries #
###################################

load("//third_party:third_party.bzl", "load_third_party_libraries")

load_third_party_libraries()

#########################################
# Set up required third party libraries #
#########################################

load("//third_party:transitive_dependencies.bzl", "load_transitive_dependencies")

load_transitive_dependencies()

################################
# Load pip Python dependencies #
################################

load("//python/dependencies:dependencies.bzl", "load_python_dependencies")

load_python_dependencies()

################################
# Load Maven Java dependencies #
################################

load("//third_party/rules_jvm_external:setup.bzl", "call_rules_jvm_external_setup")

call_rules_jvm_external_setup()

load("//java/dependencies:dependencies.bzl", "load_java_dependencies")

load_java_dependencies()
