load("//macros:cpp_testing.bzl", "cc_tested_library")

cc_tested_library(
    name = "my_lib",
    srcs = ["my_lib.cpp"],
    hdrs = ["my_lib.h"],
    tests = ["my_lib_test.cpp"],
)

cc_tested_library(
    name = "my_other_lib",
    srcs = ["my_other_lib.cpp"],
    hdrs = ["my_other_lib.h"],
    tests = ["my_other_lib_test.cpp"],
)
